local afc0_routeSets

afc0_routeSets={
	--TODO: add other cp common routes once they are solidified
	quest_cp={
		priority={
			"groupA",
		},
		sneak_day={
			groupA={
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
			},
		},
		sneak_night={
			groupA={
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
			},
		},
		caution={
			groupA={
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
				"rt_quest_dummy_0000",
			},
		},
		hold={
			default={
			},
		},
		sleep={
			default={
			},
		},
		travel={
			lrrpHold={
			},
		},
	},--quest_cp
}--afc0_routeSets
return afc0_routeSets
